### PR TITLE
update minimist, node-fetch, axios and node-forge dependencies

### PR DESCRIPTION
**Pull request by JacqueGM**
update  nested dependencies:
- minimist
- node-fetch
- axios
- node-forge
- 
update dependencies
- @graphprotocol/graph-cli
-  @graphprotocol/graph-ts
-  truffle

### CODE REVIEW

**Comment by JacqueGM** [comment]
Core test passed:
API: 1.3.22
CORE: 2.10.11
SUBGRAPH: v1.2.1-12-gdc0f767

**Comment by JacqueGM** [comment]
Core test passed:
API: 1.3.22
CORE: 2.10.11
SUBGRAPH: v1.2.1-12-gdc0f767

**Comment by llunaCreixent** [comment]
The tests don't pass for me:
API: 1.3.22
CORE: 2.10.11
SUBGRAPH: v1.3.0

**Comment by JacqueGM** [comment]
PASS  test/token.test.js (420.227 s)
 PASS  test/organization.test.js (163.959 s)
 PASS  test/safe.test.js (153.17 s)
 PASS  test/utils.test.js (36.1 s)
 PASS  test/activity.test.js (100.225 s)
 PASS  test/trust.test.js (95.97 s)
 PASS  test/user.test.js
 PASS  test/common.test.js
 PASS  test/lib.test.js

Test Suites: 9 passed, 9 total
Tests:       56 passed, 56 total
Snapshots:   0 total
Time:        972.585 s

Test pass with
API: 1.3.22
CORE: 2.10.11
SUBGRAPH: v1.3.0

If they don't pass it must be something with the dockers...

**Pull request merged**
