### PR TITLE
Update subgraph dependencies

### PR DESCRIPTION
**Pull request by llunaCreixent**
Related to: https://github.com/CirclesUBI/circles-docker/issues/33

### CODE REVIEW

**Comment by llunaCreixent** [comment]
We should update the tag in `CirclesUBI/circles-subgraph` and `CirclesUBI/circles-docker/scripts/deploy-subgraph.sh` too.

**Comment by adzialocha** [comment]
I've downgraded the graph dependencies to version `0.16.0` to avoid running into this error here (https://github.com/CirclesUBI/circles-subgraph/commit/70227983a17da58404ef4837c05abe3afaa3eb43):

```
4/6/2021, 9:19:31 AM
error

Subgraph instance failed to run: Heap access out of bounds. Offset: 28 Size: 7929961 wasm backtrace: 0: 0x12d4 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call 1: 0x1315 - <unknown>!src/types/templates/Token/Token/Token#balanceOf 2: 0x184e - <unknown>!src/token/handleTransfer in handler `handleTransfer` at block #12541947 (06e58d25fe791b3ac289f0e64c9e82c4491f71dba9e9590f2f99ab9ca4e1191d), code: SubgraphSyncingFailure, id: QmYix4iDuvRkHQMTXVBzKkUSPDnEoT3h7qKr5Sv3sBxYyE

4/6/2021, 9:19:31 AM

error

Handler skipped due to execution failure, error: Heap access out of bounds. Offset: 28 Size: 7929961 wasm backtrace: 0: 0x12d4 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call 1: 0x1315 - <unknown>!src/types/templates/Token/Token/Token#balanceOf 2: 0x184e - <unknown>!src/token/handleTransfer , handler: handleTransfer, runtime_host: 1/1, block_hash: 0x06e58d25fe791b3ac289f0e64c9e82c4491f71dba9e9590f2f99ab9ca4e1191d, block_number: 12541947

4/6/2021, 9:19:31 AM

info

Done processing Ethereum trigger, waiting_ms: 0, handler: handleTransfer, total_ms: 3, trigger_type: Log, address: 0x333d…09d2, signature: Transfer(indexed address,indexed address,uint256), runtime_host: 1/1, block_hash: 0x06e58d25fe791b3ac289f0e64c9e82c4491f71dba9e9590f2f99ab9ca4e1191d, block_number: 12541947

4/6/2021, 9:19:31 AM

info

1 trigger found in this block for the new data sources, block_hash: 0x06e58d25fe791b3ac289f0e64c9e82c4491f71dba9e9590f2f99ab9ca4e1191d, block_number: 12541947
```

Before we upgrade them again we would need to fix this first :cry:

**Review by adzialocha — CHANGES_REQUESTED** [review]
I've downgraded the graph dependencies to version `0.16.0` to avoid running into this error here (https://github.com/CirclesUBI/circles-subgraph/commit/70227983a17da58404ef4837c05abe3afaa3eb43):

```
4/6/2021, 9:19:31 AM
error

Subgraph instance failed to run: Heap access out of bounds. Offset: 28 Size: 7929961 wasm backtrace: 0: 0x12d4 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call 1: 0x1315 - <unknown>!src/types/templates/Token/Token/Token#balanceOf 2: 0x184e - <unknown>!src/token/handleTransfer in handler `handleTransfer` at block #12541947 (06e58d25fe791b3ac289f0e64c9e82c4491f71dba9e9590f2f99ab9ca4e1191d), code: SubgraphSyncingFailure, id: QmYix4iDuvRkHQMTXVBzKkUSPDnEoT3h7qKr5Sv3sBxYyE

4/6/2021, 9:19:31 AM

error

Handler skipped due to execution failure, error: Heap access out of bounds. Offset: 28 Size: 7929961 wasm backtrace: 0: 0x12d4 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call 1: 0x1315 - <unknown>!src/types/templates/Token/Token/Token#balanceOf 2: 0x184e - <unknown>!src/token/handleTransfer , handler: handleTransfer, runtime_host: 1/1, block_hash: 0x06e58d25fe791b3ac289f0e64c9e82c4491f71dba9e9590f2f99ab9ca4e1191d, block_number: 12541947

4/6/2021, 9:19:31 AM

info

Done processing Ethereum trigger, waiting_ms: 0, handler: handleTransfer, total_ms: 3, trigger_type: Log, address: 0x333d…09d2, signature: Transfer(indexed address,indexed address,uint256), runtime_host: 1/1, block_hash: 0x06e58d25fe791b3ac289f0e64c9e82c4491f71dba9e9590f2f99ab9ca4e1191d, block_number: 12541947

4/6/2021, 9:19:31 AM

info

1 trigger found in this block for the new data sources, block_hash: 0x06e58d25fe791b3ac289f0e64c9e82c4491f71dba9e9590f2f99ab9ca4e1191d, block_number: 12541947
```

Before we upgrade them again we would need to fix this first :cry:

**Comment by llunaCreixent** [comment]
Upgrading to v0.20 didn't fix anything :( 
The commits I pushed are useless :(

**Pull request closed without merging**
