### PR TITLE
Update minor dep

### PR DESCRIPTION
**Pull request by llunaCreixent**
I did `nvm use 14` (with npm v7), `npm update` and edit `package.json`.

### CODE REVIEW

**Comment by JacqueGM** [comment]
can you build an image with a dirty commit - to test with dockers?

**Comment by llunaCreixent** [comment]
> can you build an image with a dirty commit - to test with dockers?

You can also do `git checkout update-minor-dep`.

**Comment by JacqueGM** [comment]
> 

truuuuue!! 🏃

**Comment by llunaCreixent** [comment]
> > 
> 
> truuuuue!! runner

And I created the tag: https://github.com/CirclesUBI/circles-subgraph/tree/v1.3.1-0ae5d13

**Comment by JacqueGM** [comment]
core test pass :) 
api: 1.6.0
relayer: 4.1.11

LGTM 🌞

**Review by JacqueGM — APPROVED** [review]

**Pull request merged**
